# Project deploy

image: composer:2.0

pipelines:
  branches:
    stage:
      - step:
          name: Deploy
          deployment: staging
          script:
            - chmod +x deployer.phar && ./deployer.phar deploy
