---
# tasks file for rucred

- name: Clone repo into path for prepare deploy
  ansible.builtin.git:
    repo: git@bitbucket.org:rukred/rucred-crm.git
    dest: "{{ temp_repo_path }}"
    version: master
  register: code_upload
  tags: deploy

- name: Synchronize file from deploy folder to floder deployed
  shell: rsync -zvarc --exclude 'logs' "{{ temp_repo_path }}"/* "{{ tmp_repo_path }}/.git"  /home/rucred-crm/rucred-crm/ 
  when: code_upload.changed
  tags: deploy
